---
dependency:
  name: shell
  command: ./dependencies.sh
# dependency:
#   name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: almalinux9
    box: almalinux/9
    cpus: 8
    memory: 6000
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../../"
  #   ANSIBLE_VERBOSITY: 3
verifier:
  name: ansible
